spring:
  application:
    name: Api-Gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Security-Service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/auth/**

        - id: User-Service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/v1/api/user/**

        - id: Mock-Service
          uri: lb://MOCK-SERVICE
          predicates:
            - Path=/v1/api/mock/**
          filters:
            - AuthenticationFilter

        - id: Video-Service
          uri: lb://VIDEO-SERVICE
          predicates:
            - Path=/v1/api/video/**
          filters:
            - AuthenticationFilter


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080


