spring:
  application:
    name: Security-Service
  config:
    import: optional:configserver:http://localhost:8888

feign:
  hystrix:
    enabled: true



server:
  port: 0



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: info

